In [1]:
import numpy as np 

import scipy.linalg as la
import scipy
from scipy.linalg import expm, sinm, cosm

import sympy
from sympy import Matrix


In [2]:
h = sympy.Symbol("h",real= True)
P = Matrix([ [-1,1,0],
               [0,-1,1],
               [0,0,1]   ])
D = Matrix([ [-2,1,0],
               [1,-2,1],
               [0,1,-2]  ])

# matrix P

In [ ]:
P

In [ ]:
P.is_diagonal()

In [ ]:
P.is_diagonalizable()

In [ ]:
P1, Ja = P.jordan_form()

In [ ]:
Ja

In [ ]:
P1

In [ ]:
P1 * Ja * P1.inv()

In [ ]:
f = sympy.E**h
f

In [ ]:
res = P1 * (Ja*f) * P1.inv()
res

# Matrix D

In [ ]:
D

In [ ]:
D.is_diagonalizable()

In [ ]:
Q,D1=D.diagonalize()

In [ ]:
D1

In [ ]:
Q

In [ ]:
Q.inv()

In [ ]:
D1 * sympy.E**h

In [ ]:
Q * (D1 * sympy.E**h) * Q.inv()

## High Dimention

In [ ]:
A = Matrix([ [1,2,3],[4,5,6]]) #,[7,8,9]
m,n=A.shape
np.zeros(A.shape)

In [ ]:

x = sympy.Symbol("x")
f = sympy.Function("f")(x)
def Jordan_block_F(Ja):
    B = np.zeros(A.shape)
    m ,n = A.shape
    for i in range(m):
        a = 0
        for j in range(i,n):
            g=f.diff(x,a)                                    #这里是错的 应该是Jordan块的阶次  先分解为约旦块才行
            x = A[i,j]
            B[i,j] = g(x)
            a+=1
    B = Matrix(B)
    return B

# test others

In [ ]:
# expm( np.array([ [2,0],[0,3] ]) )
# expm( np.array([ [2,0],[0,3] ] * h ))  
# expm( np.array( [ [2,0],[0,3]  ])* h )  
# expm( h * Matrix( [ [2,0],[0,3]  ])  ) 

In [3]:
# expm( Matrix([[2,0],[0,3]]) )  # wrong
# expm( h* np.array([[2,0],[0,3]]) ) 
expm( np.array([[2,0],[0,3]]) ) 

array([[ 7.3890561 ,  0.        ],
       [ 0.        , 20.08553692]])

In [13]:
expm( Matrix([[2,0],[0,3]]) )  # wrong, must array

AttributeError: 'MutableDenseMatrix' object has no attribute 'dtype'

In [12]:
h = sympy.Symbol("h")
expm( h* np.array([[2,0],[0,3]]) ) 

TypeError: can't convert expression to float

In [6]:
h = 3 # h is symbol
expm( h* np.array([[2,0],[0,3]]) )  # can be solve numerically

array([[ 403.42879349,    0.        ],
       [   0.        , 8103.08392758]])

In [15]:
h* np.array([[2,0],[0,3]])

array([[2*h, 0],
       [0, 3*h]], dtype=object)

In [20]:
A = Matrix([[2,0],[0,3]])
h*A

Matrix([
[2*h,   0],
[  0, 3*h]])

In [21]:
f = sympy.E**(h*A)

TypeError: unsupported operand type(s) for ** or pow(): 'Exp1' and 'MutableDenseMatrix'

In [22]:
A = np.array([[2,0],[0,3]])
f = sympy.E**(h*A)
f

array([[exp(2*h), 1],
       [1, exp(3*h)]], dtype=object)

# scipy idea

In [ ]:
import numpy as np 
from scipy.linalg import expm, sinm, cosm
expm(np.zeros((2,2)))

 Euler’s identity $ (exp(i*\theta) = cos(\theta) + i*sin(\theta)) $ applied  to a matrix: 


In [ ]:
a = np.array([[1.0, 2.0], [-1.0, 3.0]])
expm(1j*a)

In [ ]:
cosm(a) + 1j*sinm(a)

### 自由 矩阵函数

In [ ]:
from scipy.linalg import funm
import numpy as np 
a = np.array([[1.0, 3.0], [1.0, 4.0]])
funm(a, lambda x: x*x)

In [ ]:
a.dot(a)

In [ ]:
from scipy.linalg import eigh
def funm_herm(a, func, check_finite=False):
    w, v = eigh(a, check_finite=check_finite)
    ## if you further know that your matrix is positive semidefinite,
    ## you can optionally guard against precision errors by doing
    # w = np.maximum(w, 0)
    w = func(w)
    return (v * w).dot(v.conj().T)

In [10]:
expm( np.array([[2,0],[0,3]]) ) 

array([[ 7.3890561 ,  0.        ],
       [ 0.        , 20.08553692]])

In [11]:
x = 3
expm( x * np.array([[2,1],[7,3]]) )   # Can be solved numerically

array([[2371846.83476555, 1081759.23958229],
       [7572314.67707605, 3453606.07434784]])