# Chapter 2: Vectors, matrices and multidimensional arrays

Robert Johansson

Source code listings for [Numerical Python - A Practical Techniques Approach for Industry](http://www.apress.com/9781484205549) (ISBN 978-1-484205-54-9).

The source code listings can be downloaded from http://www.apress.com/9781484205549

In [1]:
import numpy as np

## The NumPy array object

In [2]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
type(data)

numpy.ndarray

In [4]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
data.ndim

2

In [6]:
data.shape

(3, 2)

In [7]:
data.size

6

In [8]:
data.dtype

dtype('int32')

In [9]:
data.nbytes

24

## Data types

In [10]:
np.array([1, 2, 3], dtype=np.int)

array([1, 2, 3])

In [11]:
np.array([1, 2, 3], dtype=np.float)

array([1., 2., 3.])

In [12]:
np.array([1, 2, 3], dtype=np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [13]:
data = np.array([1, 2, 3], dtype=np.float)

In [14]:
data

array([1., 2., 3.])

In [15]:
data.dtype

dtype('float64')

In [16]:
data = np.array([1, 2, 3], dtype=np.int)

In [17]:
data.dtype

dtype('int32')

In [18]:
data

array([1, 2, 3])

In [19]:
data = np.array([1, 2, 3], dtype=np.float)

In [20]:
data

array([1., 2., 3.])

In [21]:
data.astype(np.int)

array([1, 2, 3])

In [22]:
d1 = np.array([1, 2, 3], dtype=float)

In [23]:
d2 = np.array([1, 2, 3], dtype=complex)

In [24]:
d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [25]:
(d1 + d2).dtype

dtype('complex128')

In [26]:
np.sqrt(np.array([-1, 0, 1]))

array([nan,  0.,  1.])

In [27]:
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([0.+1.j, 0.+0.j, 1.+0.j])

### Real and imaginary parts

In [28]:
data = np.array([1, 2, 3], dtype=complex)

In [29]:
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [30]:
data.real

array([1., 2., 3.])

In [31]:
data.imag

array([0., 0., 0.])

## Creating arrays

### Arrays created from lists and other array-like objects

In [32]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [33]:
data.ndim

1

In [34]:
data.shape

(3,)

In [35]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [36]:
data.ndim

1

In [37]:
data.shape

(3,)

### Arrays filled with constant values

In [38]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.ones(4)

array([1., 1., 1., 1.])

In [40]:
data = np.ones(4)

In [41]:
data.dtype

dtype('float64')

In [42]:
data = np.ones(4, dtype=np.int64)

In [43]:
data.dtype

dtype('int64')

In [44]:
x1 = 5.4 * np.ones(10)

In [45]:
x2 = np.full(10, 5.4)

In [46]:
x1 = np.empty(5)

In [47]:
x1.fill(3.0)

In [48]:
x1

array([3., 3., 3., 3., 3.])

In [49]:
x2 = np.full(5, 3.0)

In [50]:
x2

array([3., 3., 3., 3., 3.])

### Arrays filled with incremental sequences

In [51]:
np.arange(0.0, 10, 1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [52]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Arrays filled with logarithmic sequences

In [53]:
np.logspace(0, 2, 5)  # 5 data points between 10**0=1 to 10**2=100

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

### Mesh-grid arrays

In [54]:
x = np.array([-1, 0, 1])

In [55]:
y = np.array([-2, 0, 2])

In [56]:
X, Y = np.meshgrid(x, y)

In [57]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [58]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [59]:
Z = (X + Y) ** 2

In [60]:
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]], dtype=int32)

### Creating uninitialized arrays

In [61]:
np.empty(3, dtype=np.float)

array([0., 0., 0.])

### Creating arrays with properties of other arrays

In [62]:
def f(x):
    y = np.ones_like(x)
    # compute with x and y
    return y

### Creating matrix arrays

In [63]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [64]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [65]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [66]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

## Index and slicing

### One-dimensional arrays

In [67]:
a = np.arange(0, 11)

In [68]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
a[0]  # the first element

0

In [70]:
a[-1] # the last element

10

In [71]:
a[4]  # the fifth element, at index 4

4

In [72]:
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

In [74]:
a[:5]

array([0, 1, 2, 3, 4])

In [75]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [76]:
a[::-2]


array([10,  8,  6,  4,  2,  0])

## Multidimensional arrays

In [77]:
f = lambda m, n: n + 10 * m

In [78]:
A = np.fromfunction(f, (6, 6), dtype=int)

In [79]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [80]:
A[:, 1]  # the second column

array([ 1, 11, 21, 31, 41, 51])

In [81]:
A[1, :]  # the second row

array([10, 11, 12, 13, 14, 15])

In [82]:
A[:3, :3]  # upper half diagonal block matrix

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [83]:
A[3:, :3]  # lower left off-diagonal block matrix

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [84]:
A[::2, ::2]  # every second element starting from 0, 0

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [85]:
A[1::2, 1::3]  # every second element starting from 1, 1

array([[11, 14],
       [31, 34],
       [51, 54]])

### Views

In [86]:
B = A[1:5, 1:5]

In [87]:
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [88]:
B[:, :] = 0

In [89]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [90]:
C = B[1:3, 1:3].copy()

In [91]:
C

array([[0, 0],
       [0, 0]])

In [92]:
C[:, :] = 1  # this does not affect B since C is a copy of the view B[1:3, 1:3]

In [93]:
C

array([[1, 1],
       [1, 1]])

In [94]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Fancy indexing and Boolean-valued indexing

In [95]:
A = np.linspace(0, 1, 11)

In [96]:
A[np.array([0, 2, 4])]

array([0. , 0.2, 0.4])

In [97]:
A[[0, 2, 4]]

array([0. , 0.2, 0.4])

In [98]:
A > 0.5 

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [99]:
A[A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [100]:
A = np.arange(10)

In [101]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
indices = [2, 4, 6]

In [103]:
B = A[indices]

In [104]:
B[0] = -1  # this does not affect A

In [105]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
A[indices] = -1

In [107]:
A

array([ 0,  1, -1,  3, -1,  5, -1,  7,  8,  9])

In [108]:
A = np.arange(10)

In [109]:
B = A[A > 5]

In [110]:
B[0] = -1  # this does not affect A

In [111]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
A[A > 5] = -1

In [113]:
A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

## Reshaping and resizing

In [114]:
data = np.array([[1, 2], [3, 4]])

In [115]:
np.reshape(data, (1, 4))

array([[1, 2, 3, 4]])

In [116]:
data.reshape(4)

array([1, 2, 3, 4])

In [117]:
data = np.array([[1, 2], [3, 4]])

In [118]:
data

array([[1, 2],
       [3, 4]])

In [119]:
data.flatten()

array([1, 2, 3, 4])

In [120]:
data.flatten().shape

(4,)

In [121]:
data = np.arange(0, 5)

In [122]:
column = data[:, np.newaxis]

In [123]:
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [124]:
row = data[np.newaxis, :]

In [125]:
row

array([[0, 1, 2, 3, 4]])

In [126]:
data = np.arange(5)

In [127]:
data

array([0, 1, 2, 3, 4])

In [128]:
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [129]:
data = np.arange(5)

In [130]:
data

array([0, 1, 2, 3, 4])

In [131]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [132]:
data = data[:, np.newaxis]

In [133]:
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

## Vectorized expressions

### Arithmetic operations

In [134]:
x = np.array([[1, 2], [3, 4]]) 

In [135]:
y = np.array([[5, 6], [7, 8]])

In [136]:
x + y

array([[ 6,  8],
       [10, 12]])

In [137]:
y - x

array([[4, 4],
       [4, 4]])

In [138]:
x * y

array([[ 5, 12],
       [21, 32]])

In [139]:
y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [140]:
x * 2

array([[2, 4],
       [6, 8]])

In [141]:
2 ** x

array([[ 2,  4],
       [ 8, 16]], dtype=int32)

In [142]:
y / 2

array([[2.5, 3. ],
       [3.5, 4. ]])

In [143]:
(y / 2).dtype

dtype('float64')

In [144]:
x = np.array([1, 2, 3, 4]).reshape(2,2)

In [145]:
z = np.array([1, 2, 3, 4])

In [146]:
x / z

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

In [ ]:
z = np.array([[2, 4]])

In [ ]:
z

In [ ]:
z.shape

In [ ]:
x / z

In [ ]:
zz = np.concatenate([z, z], axis=0)

In [ ]:
zz

In [ ]:
x / zz

In [ ]:
z = np.array([[2], [4]])

In [ ]:
z.shape

In [ ]:
x / z

In [ ]:
zz = np.concatenate([z, z], axis=1)

In [ ]:
zz

In [ ]:
x / zz

In [ ]:
x = np.array([[1, 3], [2, 4]])
x = x + y
x

In [ ]:
x = np.array([[1, 3], [2, 4]])
x += y
x

### Elementwise functions

In [ ]:
x = np.linspace(-1, 1, 11)

In [ ]:
x

In [ ]:
y = np.sin(np.pi * x)

In [ ]:
np.round(y, decimals=4)

In [ ]:
np.add(np.sin(x) ** 2, np.cos(x) ** 2)

In [ ]:
np.sin(x) ** 2 + np.cos(x) ** 2

In [ ]:
def heaviside(x):
    return 1 if x > 0 else 0

In [ ]:
heaviside(-1)

In [ ]:
heaviside(1.5)

In [ ]:
x = np.linspace(-5, 5, 11)

In [ ]:
heaviside(x)

In [ ]:
heaviside = np.vectorize(heaviside)

In [ ]:
heaviside(x)

In [ ]:
def heaviside(x):
    return 1.0 * (x > 0)

### Aggregate functions

In [ ]:
data = np.random.normal(size=(15,15))

In [ ]:
np.mean(data)

In [ ]:
data.mean()

In [ ]:
data = np.random.normal(size=(5, 10, 15))

In [ ]:
data.sum(axis=0).shape

In [ ]:
data.sum(axis=(0, 2)).shape

In [ ]:
data.sum()

In [ ]:
data = np.arange(1,10).reshape(3,3)

In [ ]:
data

In [ ]:
data.sum()

In [ ]:
data.sum(axis=0)

In [ ]:
data.sum(axis=1)

### Boolean arrays and conditional expressions

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
b = np.array([4, 3, 2, 1])

In [ ]:
a < b

In [ ]:
np.all(a < b)

In [ ]:
np.any(a < b)

In [ ]:
if np.all(a < b):
    print("All elements in a are smaller than their corresponding element in b")
elif np.any(a < b):
    print("Some elements in a are smaller than their corresponding elemment in b")
else:
    print("All elements in b are smaller than their corresponding element in a")

In [ ]:
x = np.array([-2, -1, 0, 1, 2])

In [ ]:
x > 0

In [ ]:
1 * (x > 0)

In [ ]:
x * (x > 0)

In [ ]:
def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))

In [ ]:
x = np.linspace(-5, 5, 11)

In [ ]:
pulse(x, position=-2, height=1, width=5)

In [ ]:
pulse(x, position=1, height=1, width=5)

In [ ]:
def pulse(x, position, height, width):
    return height * np.logical_and(x >= position, x <= (position + width))

In [ ]:
x = np.linspace(-4, 4, 9)

In [ ]:
np.where(x < 0, x**2, x**3)

In [ ]:
np.select([x < -1, x < 2, x >= 2],
          [x**2  , x**3 , x**4])

In [ ]:
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2], 
          [x**2,    x**3,    x**4])

In [ ]:
x[abs(x) > 2]

In [ ]:
np.nonzero(abs(x) > 2)

In [ ]:
x[np.nonzero(abs(x) > 2)]

# Set operations

In [ ]:
a = np.unique([1,2,3,3])

In [ ]:
b = np.unique([2,3,4,4,5,6,5])

In [ ]:
np.in1d(a, b)

In [ ]:
1 in a

In [ ]:
1 in b

In [ ]:
np.all(np.in1d(a, b))

In [ ]:
np.union1d(a, b)

In [ ]:
np.intersect1d(a, b)

In [ ]:
np.setdiff1d(a, b)

In [ ]:
np.setdiff1d(b, a)

### Operations on arrays

In [ ]:
data = np.arange(9).reshape(3, 3)

In [ ]:
data

In [ ]:
np.transpose(data)

In [ ]:
data = np.random.randn(1, 2, 3, 4, 5)

In [ ]:
data.shape

In [ ]:
data.T.shape

## Matrix and vector operations

In [ ]:
A = np.arange(1, 7).reshape(2, 3)

In [ ]:
A

In [ ]:
B = np.arange(1, 7).reshape(3, 2)

In [ ]:
B

In [ ]:
np.dot(A, B)

In [ ]:
np.dot(B, A)

In [ ]:
A = np.arange(9).reshape(3, 3)

In [ ]:
A

In [ ]:
x = np.arange(3)

In [ ]:
x

In [ ]:
np.dot(A, x)

In [ ]:
A.dot(x)

In [ ]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)

In [ ]:
Ap = B @ A @ np.linalg.inv(B)
Ap

In [ ]:
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))
Ap

In [ ]:
Ap = B.dot(A.dot(np.linalg.inv(B)))
Ap

In [ ]:
A = np.matrix(A)

In [ ]:
B = np.matrix(B)

In [ ]:
Ap = B * A * B.I

In [ ]:
A = np.asmatrix(A)

In [ ]:
B = np.asmatrix(B)

In [ ]:
Ap = B * A * B.I

In [ ]:
Ap = np.asarray(Ap)

In [ ]:
Ap

In [ ]:
np.inner(x, x)

In [ ]:
np.dot(x, x)

In [ ]:
y = x[:, np.newaxis]

In [ ]:
y

In [ ]:
np.dot(y.T, y)

In [ ]:
x = np.array([1, 2, 3])

In [ ]:
np.outer(x, x) 

In [ ]:
np.kron(x, x) 

In [ ]:
np.kron(x[:, np.newaxis], x[np.newaxis, :])

In [ ]:
np.kron(np.ones((2,2)), np.identity(2))

In [ ]:
np.kron(np.identity(2), np.ones((2,2)))

In [ ]:
x = np.array([1, 2, 3, 4])

In [ ]:
y = np.array([5, 6, 7, 8])

In [ ]:
np.einsum("n,n", x, y)

In [ ]:
np.inner(x, y)

In [ ]:
A = np.arange(9).reshape(3, 3)

In [ ]:
B = A.T

In [ ]:
np.einsum("mk,kn", A, B)

In [ ]:
np.alltrue(np.einsum("mk,kn", A, B) == np.dot(A, B))

# Versions

In [ ]:
%reload_ext version_information
%version_information numpy