In [1]:
from scipy.linalg import lu_factor
import numpy as np 

In [2]:
A = np.array([[2, 5, 8, 7], 
              [5, 2, 2, 8], 
              [7, 5, 6, 6], 
              [5, 4, 4, 8]])
lu, piv = lu_factor(A)

In [3]:
lu

array([[ 7.        ,  5.        ,  6.        ,  6.        ],
       [ 0.28571429,  3.57142857,  6.28571429,  5.28571429],
       [ 0.71428571,  0.12      , -1.04      ,  3.08      ],
       [ 0.71428571, -0.44      , -0.46153846,  7.46153846]])

In [4]:
piv

array([2, 2, 3, 3], dtype=int32)

In [12]:
piv_py = [2, 0, 3, 1]
A[piv_py]  # = L@U

array([[7, 5, 6, 6],
       [2, 5, 8, 7],
       [5, 4, 4, 8],
       [5, 2, 2, 8]])

In [5]:
L, U = np.tril(lu, k=-1) + np.eye(4), np.triu(lu) #返回上下三角

In [13]:
A[piv_py]-L@U #############################################

array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 0.0000000e+00, 4.4408921e-16, 0.0000000e+00],
       [8.8817842e-16, 0.0000000e+00, 4.4408921e-16, 0.0000000e+00]])

array([[-3., -5., 18.,  1.],
       [ 8., -5., -2.,  1.],
       [ 9., -4., 14., -2.],
       [ 5., -2., 10.,  0.]])

In [6]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.28571429,  1.        ,  0.        ,  0.        ],
       [ 0.71428571,  0.12      ,  1.        ,  0.        ],
       [ 0.71428571, -0.44      , -0.46153846,  1.        ]])

In [7]:
U

array([[ 7.        ,  5.        ,  6.        ,  6.        ],
       [ 0.        ,  3.57142857,  6.28571429,  5.28571429],
       [ 0.        ,  0.        , -1.04      ,  3.08      ],
       [ 0.        ,  0.        ,  0.        ,  7.46153846]])

In [8]:
L@U

array([[7., 5., 6., 6.],
       [2., 5., 8., 7.],
       [5., 4., 4., 8.],
       [5., 2., 2., 8.]])

In [9]:
A.dot(A)

array([[120,  88, 102, 158],
       [ 74,  71,  88, 127],
       [111,  99, 126, 173],
       [ 98,  85, 104, 155]])

In [10]:
A.T@A

array([[103,  75,  88, 136],
       [ 75,  70,  90, 113],
       [ 88,  90, 120, 140],
       [136, 113, 140, 213]])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])