In [1]:
import numpy as np 

人们有时会说，与C++这种低级语言相比，Python以运行速度为代价改善了开发时间和效率。幸运的是，有一些方法可以在不牺牲易用性的情况下加速Python中的操作运行时。适用于快速数值运算的一个选项是NumPy，它当之无愧地将自己称为使用Python进行科学计算的基本软件包。

当然，很少有人将50微秒（百万分之五十秒）的东西归类为“慢”。然而，计算机可能会有所不同。运行50微秒（50微秒）的运行时属于微执行领域，可以松散地定义为运行时间在1微秒和1毫秒之间的运算。

为什么速度很重要？微观性能值得监控的原因是运行时的小差异会随着重复的函数调用而放大：增量50μs的开销，重复超过100万次函数调用，转换为50秒的增量运行时间。

在计算方面，实际上有三个概念为NumPy提供了强大的功能：

矢量化
广播
索引

在本教程中，你将逐步了解如何利用矢量化和广播，以便你可以充分使用NumPy。虽然你在这里将使用一些索引，但NumPy的完整索引原理图(它扩展了Python的切片语法)是它们自己的工具。如果你想了解有关NumPy索引的更多信息，请喝点咖啡，然后前往NumPy文档中的索引部分。

#进入状态：介绍NumPy数组

In [2]:
arr = np.arange(36).reshape(3, 4, 3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

什么是矢量化？
矢量化是NumPy中的一种强大功能，可以将操作表达为在整个数组上而不是在各个元素上发生。以下是Wes McKinney的简明定义：

这种用数组表达式替换显式循环的做法通常称为向量化。通常，矢量化数组操作通常比其纯Python等价物快一个或两个（或更多）数量级，在任何类型的数值计算中都具有最大的影响。查看源码

在Python中循环数组或任何数据结构时，会涉及很多开销。 NumPy中的向量化操作将内部循环委托给高度优化的C和Fortran函数，从而实现更清晰，更快速的Python代码

In [3]:
np.random.seed(444)
x = np.random.choice([False, True], size=100000)
x

array([ True, False,  True, ...,  True, False,  True])

使用Python for循环，一种方法是成对地评估序列中每个元素的真值以及紧随其后的元素：

In [6]:
def count_transitions(x) -> int:
    count = 0
    for i,j in zip(x[:-1],x[1:]):
        if j and not i:
            count+=1
    return count
count_transitions(x)

24984

In [7]:
np.count_nonzero(x[:-1] < x[1:]) #在矢量化形式中，没有明确的for循环或直接引用各个元素：

24984

In [8]:
x

array([ True, False,  True, ...,  True, False,  True])