NumPy 数据分析练习

Numpy练习的目标仅作为学习numpy的参考，并让你脱离基础性的NumPy使用。这些问题有4个级别的难度，其中L1是最容易的，L4是最难的。

#NumPy数据分析问答

#1、导入numpy作为np，并查看版本

**难度等级：**L1 **问题：**将numpy导入为 np 并打印版本号。 答案：

In [1]:
import numpy as np
print(np.__version__)
# > 1.13.3

1.18.5


你必须将numpy导入np，才能使本练习中的其余代码正常工作。

要安装numpy，建议安装anaconda，里面已经包含了numpy

#2、如何创建一维数组？

**难度等级：**L1 **问题：**创建从0到9的一维数字数组

In [ ]:
arr = np.arange(10)
arr
# > array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#3. 如何创建一个布尔数组？

**难度等级：**L1

**问题：**创建一个numpy数组元素值全为True（真）的数组

In [3]:
np.full((3, 3), True, dtype=bool)
# > array([[ True,  True,  True],
# >        [ True,  True,  True],
# >        [ True,  True,  True]], dtype=bool)



array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
# Alternate method:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#4. 如何从一维数组中提取满足指定条件的元素？

**难度等级：**L1

**问题：**从 arr 中提取所有的奇数

给定：

In [8]:
# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
arr[arr % 2 ==1]
# > array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

#5. 如何用numpy数组中的另一个值替换满足条件的元素项？

**难度等级：**L1

**问题：**将arr中的所有奇数替换为-1。

In [9]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr
# > array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#6. 如何在不影响原始数组的情况下替换满足条件的元素项？

**难度等级：**L2

**问题：**将arr中的所有奇数替换为-1，而不改变arr。

In [11]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out
# > [0 1 2 3 4 5 6 7 8 9]
#array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#7. 如何改变数组的形状？

**难度等级：**L1

**问题：**将一维数组转换为2行的2维数组

In [12]:
arr = np.arange(10)
arr.reshape(2, -1)  # Setting to -1 automatically decides the number of cols
# > array([[0, 1, 2, 3, 4],
# >        [5, 6, 7, 8, 9]])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#8. 如何垂直叠加两个数组？

**难度等级：**L2

**问题：**垂直堆叠数组a和数组b

In [16]:
a = np.arange(10).reshape(2,-1)     #>>> [[0 1 2 3 4]
                                    #     [5 6 7 8 9]]
b = np.repeat(1, 10).reshape(2,-1)  #>>> [[1 1 1 1 1]
                                    #     [1 1 1 1 1]]

# Answers

# Method 1:
np.concatenate([a, b], axis=0)

# Method 2:
np.vstack([a, b])

# Method 3:
np.r_[a, b]
# > array([[0, 1, 2, 3, 4],
# >        [5, 6, 7, 8, 9],
# >        [1, 1, 1, 1, 1],
# >        [1, 1, 1, 1, 1]])

[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#9. 如何水平叠加两个数组？

**难度等级：**L2

**问题：**将数组a和数组b水平堆叠。

In [18]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Answers
# Method 1:
np.concatenate([a, b], axis=1)

# Method 2:
np.hstack([a, b])

# Method 3:
np.c_[a, b]
# > array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
# >        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

#10. 如何在无硬编码的情况下生成numpy中的自定义序列？

**难度等级：**L2

**问题：**创建以下模式而不使用硬编码。只使用numpy函数和下面的输入数组a。

给定：

a = np.array([1,2,3])`

期望的输出：

array ([1, 1, 1,2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [22]:
#np.r_[np.repeat(a,3), np.tile(a,3)]                                #???
# > array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

#11. 如何获取两个numpy数组之间的公共项？

**难度等级：**L2

**问题：**获取数组a和数组b之间的公共项。

In [23]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)
# > array([2, 4])

array([2, 4])