In [ ]:
import numpy as np

In [ ]:
#数组基础
#创建一个数组
a = np.array([0,1,2,3,4])
b = np.array((0,1,2,3,4))
c = np.arange(5)
d = np.linspace(0,2*np.pi,5)
print(a) # >>>[0 1 2 3 4]
print(b) # >>>[0 1 2 3 4]
print(c) # >>>[0 1 2 3 4]
print(d) # >>>[ 0.          1.57079633  3.14159265  4.71238898  6.28318531]
print(a[3]) # >>>3

In [ ]:
#如何使用多维数组表示矩阵和更多的信息
# MD Array,
a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35]])   #  注意逗号
 
print(a[2,4]) # >>>25
# 为了创建一个2D（二维）数组，我们传递一个列表的列表（或者是一个序列的序列）给array()函数。如果我们想要一个3D（三维）数组，我们就要传递一个列表的列表的列表，如果是一个4D（四维）数组，那就是列表的列表的列表的列表，以此类推。

# 请注意2D（二维）数组（在我们的朋友空格键的帮助下）是如何按行和列排列的。要索引2D（二维）数组，我们只需引用行数和列数即可

In [ ]:
#在NumPy中，我们通过传递一系列序列来制作数组

In [ ]:
#多维数组切片 # MD slicing
#切片多维数组比1D数组复杂一点，并且在使用NumPy时你也会经常需要使用到。
print(a[0, 1:4]) # >>>[12 13 14]
print(a[1:4, 0]) # >>>[16 21 26]

print(a[0,::2])  #  >>>[11 13 15] 第一行 间隔切片
print(a[::2,0])  #  >>>[11 21 31] 第一列 每隔两个切片
print(a[::2,::2]) # >>>[[11 13 15]
                  #     [21 23 25]
                  #     [31 33 35]]

print(a[:, 1]) # >>>[12 17 22 27 32]
                                    #对于2D数组，我们的第一片定义了行的切片，第二片定义了列的切片


In [ ]:
#在使用 NumPy 时，你会想知道数组的某些信息。很幸运，在这个包里边包含了很多便捷的方法，可以给你想要的信息
# Array properties
print(type(a)) # >>><class 'numpy.ndarray'>
print(a.dtype) # >>>int64
print(a.size) # >>>25
print(a.shape) # >>>(5, 5)
print(a.itemsize) # >>>8   itemsize属性是每个项占用的字节数。这个数组的数据类型是int 64，一个int 64中有64位，一个字节中有8位，除以64除以8，你就可以得到它占用了多少字节，在本例中是8
print(a.ndim) # >>>2  ndim 属性是数组的维数。这个有2个。例如，向量只有1。
print(a.nbytes) # >>>200  nbytes 属性是数组中的所有数据消耗掉的字节数。你应该注意到，这并不计算数组的开销，因此数组占用的实际空间将稍微大一点。

In [ ]:
#使用数组
#基本操作符  使用四则运算符 +、- 、/ 来完成运算操作

In [ ]:
# Basic Operators
a = np.arange(25)
a = a.reshape((5, 5))

b = np.array([10, 62, 1, 14, 2, 56, 79, 2, 1, 45,
              4, 92, 5, 55, 63, 43, 35, 6, 53, 24,
              56, 3, 56, 44, 78])
b = b.reshape((5,5))

In [ ]:
print(a + b) #除了 dot() 之外，这些操作符都是对数组进行逐元素运算。比如 (a, b, c) + (d, e, f) 的结果就是 (a+d, b+e, c+f)。它将分别对每一个元素进行配对，然后对它们进行运算。
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)
print(a < b) #注意，当使用逻辑运算符比如 “<” 和 “>” 的时候，返回的将是一个布尔型数组，这点有一个很好的用处，后边我们会提到。
print(a > b)

print(a.dot(b)) #dot() 函数计算两个数组的点积。它返回的是一个标量（只有大小没有方向的一个值）而不是数组。

#dot()函数称为点积。 [a1,a2,a3].T 点积 [b1,b2,b3] = a1b1+a2b2+a3b3


In [ ]:
#数组特殊运算符  NumPy还提供了一些别的用于处理数组的好用的运算符。
# dot, sum, min, max, cumsum
a = np.arange(10) # >>>[0 1 2 3 4 5 6 7 8 9]

print(a.sum()) # >>>45              #sum()、min()和max()函数的作用非常明显。将所有元素相加，找出最小和最大元素。
print(a.min()) # >>>0
print(a.max()) # >>>9
print(a.cumsum()) # >>>[ 0  1  3  6 10 15 21 28 36 45]
                  #cumsum()函数将像sum()这样的每个元素相加，但是它首先将第一个元素和第二个元素相加，并将计算结果存储在一个列表中，然后将该结果添加到第三个元素中，然后再将该结果存储在一个列表中。这将对数组中的所有元素执行此操作，并返回作为列表的数组之和的运行总数

In [ ]:
#索引进阶

In [ ]:
#花式索引
#花式索引 是获取数组中我们想要的特定元素的有效方法。
# Fancy indexing
a = np.arange(0, 100, 10)
indices = [1, 5, -1]  # 第二个 第六个 倒数第一个
b = a[indices]
print(a) # >>>[ 0 10 20 30 40 50 60 70 80 90]
print(b) # >>>[10 50 90]
print(a[[1,5,-1]]) #直接用也是可以的 注意双括号

In [ ]:
#布尔屏蔽
#布尔屏蔽 是一个有用的功能，它允许我们根据我们指定的条件检索数组中的元素。
# Boolean masking
import matplotlib.pyplot as plt

a = np.linspace(0, 2 * np.pi, 50)   #圆周率的表示办法 np.pi
print("a= \n",a)
b = np.sin(a)
plt.plot(a,b)

mask = b >= 0
#plt.plot(a[mask], b[mask], 'bo')
plt.plot(a[b >= 0],b[b >= 0],'go')  #ps这样也是可以的啊 把条件直接写到矩阵里

mask = (b >= 0) & (a <= np.pi / 2)
plt.plot(a[mask], b[mask], 'go')

plt.show()
                                    #上面的示例显示了如何进行布尔屏蔽。你所要做的就是将数组传递给涉及数组的条件，它将为你提供一个值的数组，为该条件返回true。

In [ ]:
#缺省索引
#不完全索引是从多维数组的第一个维度获取索引或切片的一种方便方法。例如，如果数组a=[1，2，3，4，5]，[6，7，8，9，10]，那么[3]将在数组的第一个维度中给出索引为3的元素，这里是值4。
# Incomplete Indexing
a = np.arange(0, 100, 10)
b = a[:5]       # >>>[ 0 10 20 30 40]
c = a[a >= 50]  # >>>[50 60 70 80 90]
print(b) 
print(c) 

In [ ]:
#Where 函数
#where() 函数是另外一个根据条件返回数组中的值的有效方法。只需要把条件传递给它，它就会返回一个使得条件为真的元素的列表。
# Where
a = np.arange(0, 100, 10)   # >>>[ 0 10 20 30 40 50 60 70 80 90]
m = a.reshape(2,5)          # >>>[[ 0 10 20 30 40]
                                 # [50 60 70 80 90]]
print(m)
b = np.where(a < 50)        # >>>(array([0, 1, 2, 3, 4]),)
print(b) 
print(np.where(m<90))       # >>>(array([0, 0, 0, 0, 0, 1, 1, 1, 1], dtype=int64), array([0, 1, 2, 3, 4, 0, 1, 2, 3], dtype=int64)) 对应还是比较奇怪的
c = np.where(a >= 50)[0]    # >>>[5 6 7 8 9]
#print(c) 
