In [1]:
import numpy as np 


In [ ]:
x=np.random(10)
x.min #求最小值
np.min(x)

x.max #求最大值
np.max(X)

x.median()  #可能出事 有时不行
np.median(x) #求中位数 把左右两边划分相同  偶数中间两个均值

x.mean()    #均值

x.sum() #求和
x.prod()
x.percentile(x,q=50) #50%？？？？

np.var(x)  #方差
np.std(x)  #标准差

X=np.arange(16).reshape(4,-1)  #小写x代表一维数据  大写X代表二维数据
X.sum()
np.sum()
np.sum(X,axis=0) #行方向 向下求和
np.sum(X,axis=1) #列方向 横向求和

np.min(X,axis=0) #二维数据可以 设置坐标轴


In [16]:
x=np.random.normal(0,1,size=10) #正态分布 array([-0.26979046, -0.28322268, -0.12126364, -0.21413683,  0.07250951,
                                    # -0.3084301 ,  0.84486719, -0.46854392,  1.30689413,  0.20984325])
np.argmin(x) #得到的是 最小值的位置 其他同理

#排序
x=np.arange(16)
np.random.shuffle(x) #乱序
np.sort(x) #排序 从小到大   生成一个新的矩阵  原来的x保持不变

X=np.random.randint(0,10,size=(4,4))
np.sort(X) #每一行  从小大排序  axis默认为1
np.sort(X,axis=0) #每一列 排序


np.argsort(x) #返回从小大大 元素对应的位置
x[np.argsort(x)]  #排序

np.partition(x,3)   #前三个排序   拓展 前n个排序
np.argpartition(x,3) #求前三个排序 的位置； 
index=np.argpartition(x,12)
x[index[0:12] ]   #求最近的几个邻居不关心排序  机器学习时 使用

np.argsort(X,axis=0) #列方向 排序的位置

array([[9, 7, 8, 7],
       [6, 4, 5, 5],
       [5, 7, 4, 3],
       [2, 9, 4, 6]])

In [22]:
x=np.arange(16)
np.random.shuffle(x) #打乱
x[3]
x[3:9]
x[3:9:2]
np.array([ x[1],x[3],x[7] ])
#或者
index=[1,3,7] 
#index=np.array([1,3,7])
x[index]

index=np.array([ [0,2],[1,3] ])
x[index] #索引结果的维数 和index相同 和x无关。




X=x.reshape(4,-1)
row=np.array([0,1,2])
col=np.array([1,2,3])
X[row,col] #array([15,  8, 12])   #z只有一维 三个， 行号列号取一个  行号列号取一个 是坐标
X[:3,1:] #切片和index 不一样 这个是二维矩阵

#还可以传布尔型
col=[True,False,True,False]
X[1,col]


x>10 #得到布尔型数组 
x[x>10] #可以取到 条件数据   
x[ (x<3)|(x>10) ] 

2*x==24-4*x #也可以索引

X<6 #二维一样 但是
X[X<6] #索引 生成 一维的

np.sum(x<3) #返回的是小于3 的个数 而不是和
np.count_nonzero(x<3) #所有非零的值
np.any(x==0) #只要有一个符合即可
np.all(x==0)

np.sum(x%2==0) #的个数
np.sum(X%2==0) #de 个数
np.sum(X%2==0,axis=0) #计算每一列 的个数

array([15,  8, 12])

In [9]:
A=np.arange(1,5).reshape(2,-1)
B=np.full((2,2),10)
np.dot(A,B)

array([[30, 30],
       [70, 70]])

In [ ]:
#a = arange(15).reshape(3,5)
a = np.arange(15).reshape(3, 5)
print(a)
type(a)

In [ ]:
b=np.array([6,7,8])
print(b)
type(b)

In [ ]:
# Numpy中文网教程

In [ ]:
my_array = np.array([1,2,3,4,5])
print(my_array)
my_array.shape #意思就是 my_array 是一个包含5个元素的数组

In [ ]:
print(my_array[0])
print(my_array[1])      #像普通的Python数组一样，NumPy数组的起始索引编号为0。

In [ ]:
my_array[0]=-1
my_array #还可以修改NumPy数组的元素

In [ ]:
#现在假设，我们要创建一个长度为5的NumPy数组，但所有元素都为0，我们可以这样做吗？是的。NumPy提供了一种简单的方法来做同样的事情。
my_new_array = np.zeros((5))
my_new_array

In [ ]:
my_array_1 = np.ones((5)) #创建一个长度为5的NumPy数组，但所有元素都为1
my_array_1

In [ ]:
# 如果我们想创建一个随机值数组
my_random_array = np.random.random((5))
my_random_array

In [ ]:
#NumPy创建二维数组
my_2d_array = np.zeros((2,3))  
my_2d_array  

In [ ]:
my_2d_array_new = np.ones((2,4))
print(my_2d_array_new) 
print(my_2d_array_new.shape)
print(my_2d_array_new[1][0]) #多维数组可以用 my_array[i][j] 符号来索引，其中i表示行号，j表示列号。i和j都从0开始

In [ ]:
my_array_column = np.array([ [4 , 5] ,[6,1] ])
print(my_array_column)
print ( my_array_column[0][1]  )
print("shape",my_array_column.shape)

In [ ]:
my_array_column_2 = my_array_column[:,1]  
print(my_array_column_2)
print(my_array_column[:,1]) #假设，我们想从中提取第二列（索引1）的所有元素
                            #注意，我们使用了冒号(:)而不是行号，而对于列号，我们使用了值1，最终输出是：[5, 1]。

In [ ]:
a = np.array([[1.0, 2.0], 
              [3.0, 4.0]]) 
b = np.array([[5.0, 6.0], 
              [7.0, 8.0]]) 
sum = a + b 
difference = a - b 
product = a * b   #乘法运算符执行逐元素乘法而不是矩阵乘法

matrix_product = a.dot(b)  #要执行矩阵乘法，可以执行此操作

quotient = a / b 
print ("Sum = \n", sum )
print("Difference = \n", difference )
print("Product = \n", product )
print("Matrix Product= \n  ", matrix_product)
print("Quotient = \n", quotient )