NumPy 中的矩阵和向量

numpy的ndarray类用于表示矩阵和向量。 要在numpy中构造矩阵，我们在列表中列出矩阵的行， 并将该列表传递给numpy数组构造函数。

In [2]:
import numpy as np 
#例如，构造与矩阵对应的numpy数组
#[  [ 1 -1 2],
#   [ 3  2 0] ]
A = np.array([[1,-1,2],[3,2,0]])
A

array([[ 1, -1,  2],
       [ 3,  2,  0]])

In [4]:
#向量只是具有单列的数组。 例如，构建向量

# [2
#  1 
#  3]
v = np.array([[2],[1],[3]])
v

array([[2],
       [1],
       [3]])

In [6]:
#更方便的方法是转置相应的行向量。 例如，为了使上面的矢量，我们可以改为转置行向量
v = np.transpose(np.array([[2,1,3]])) 
v

array([[2],
       [1],
       [3]])

In [7]:
#numpy重载数组索引和切片符号以访问矩阵的各个部分。 例如，要打印矩阵A中的右下方条目，我们会这样做
print(A[1,2])

0


In [11]:
#要切出A矩阵中的第二列，我们会这样做
col = A[:,0:1]  #这里面的0 1 数字指的是两列之间的逗号位次（带第一列左边）
col
#第一个切片选择A中的所有行，而第二个切片仅选择每行中的中间条目。

array([[1],
       [3]])

In [16]:
#要进行矩阵乘法或矩阵向量乘法，我们使用np.dot()方法。
w = np.dot(A,v)
a = A.dot(v)
print(w,"\n",a)
print(A*A)

[[7]
 [8]] 
 [[7]
 [8]]
[[1 1 4]
 [9 4 0]]


#用numpy求解方程组

线性代数中比较常见的问题之一是求解矩阵向量方程

 这是一个例子。 我们寻找解决方程的向量x

A x = b



In [ ]:
# 当A =
#[[ 2  1 -2]
 #[ 3  0  1]
 #[ 1  1 -1]]

 #b=
 #[[-3]
 #[  5]
 #[ -2]]

In [17]:
#我们首先构建A和b的数组。
A = np.array([[2,1,-2],[3,0,1],[1,1,-1]])
b = np.transpose(np.array([[-3,5,-2]]))
print(A)
print(b)

[[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]
[[-3]
 [ 5]
 [-2]]


In [19]:
#为了解决这个系统

x = np.linalg.solve(A,b)                #求解函数！
x

array([[ 1.],
       [-1.],
       [ 2.]])

应用：多元线性回归

在多元回归问题中，我们寻找一种能够将输入数据点映射到结果值的函数。 每个数据点是特征向量（x1，x2，...，xm），由两个或多个捕获输入的各种特征的数据值组成。为了表示所有输入数据以及输出值的向量，我们设置了输入矩阵X和输出向量 y：

https://www.numpy.org.cn/article/basics/numpy_matrices_vectors.html#%E7%94%A8numpy%E6%B1%82%E8%A7%A3%E6%96%B9%E7%A8%8B%E7%BB%84